---
functional:
  - Сайт предоставляет возможность двум пользователям соревноваться друг с другом в решении задач
  - Во время соревнования участники могут видеть код друг друга
  - На сайте присутствует рейтинг пользователей за неделю, месяц, все время
  - У пользователя есть возможность создать игру, присоедениться к чужой игре, пригласить в игру конкретного пользователя, создать игру с ботом, наблюдать за чужой игрой
  - На сайте есть чат для зарегестрированных пользователей
  - Пользователь может менять язык программирования во время игры
  - Пользователь может выбрать уровень сложности игры
  - Задачи даны на двух языках - русском и английском
  - Завершенная игра доступна в записи
  - Редактор ввода кода выглядит как проигрователь
  - Пользователи получают очки, на основе которых строится рейтинг
  - Каждый игрок имеет кнопку "check" для проверки своего решения. Попыток проверки неограниченно.
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры.
  - Проигравший игрок может выйти из игры или доиграть до конца
  - Когда оба игрока вышли, игра считается полностью законченной
  - Во время матча на экране отображается задание и время игры
  - Пользователь может вернуться в игру, если она еще не завершена
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь может зарегистрироваться на сайте
  - Пользователь может изменить никнейм
  - При неверном вводе эмейла\пароля должна появляться сответствующая ошибка
  - Форма входа должна содержать поля логин\пароль и дополнительные сполосы входа, если такие имеются
  - На сайте должна храниться история игр для просмотра
  - Пользователь может восстановить пароль через электронную почту
  - В форме входа должна быть кнопка для восстановления пароля
  - Во время матча пользователь может сдаться и завершить игру
