---
functional:
  - Сайт предоставляет возможность двум пользователям соревноваться друг с другом в решении задач
  - Во время соревнования участники могут видеть код друг друга
  - На сайте присутствует рейтинг пользователей за неделю, месяц, все время
  - У пользователя есть возможность создать игру, присоедениться к чужой игре, пригласить в игру конкретного пользователя, создать игру с ботом, наблюдать за чужой игрой
  - На сайте есть чат для зарегестрированных пользователей
  - Пользователь может менять язык программирования во время игры
  - Пользователь может выбрать уровень сложности игры
  - Задачи даты на двух языках - русском и английском
  - Завершенная игра доступна в записи
  - Редактор ввода кода выглядит как проигрователь
  - Пользователи получают очки. на основе которых строится рейтинг
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - На сайте должна храниться история игр для просмотра

